### ISSUE TITLE
refactor ood playbook to separate cluster-specific and ood-specfic tasks

### ISSUE THREAD

**Issue by jprorama** [jprorama/CRI_XCBC#24]
With a fully operations ood environment with job control, terminal, and interactive desktop we are ready to use this work in other contexts.

In order to increase the range of applications for the ood role, we need to isolate tasks that are specific to ood set up (software, config files etc) from the tasks that are specific to a particular cluster environment (eg. ohpc, the default).   I'm thinking this could be done by splitting tasks across multiple playbooks, but there may be a more ansible recommended approach.  This issue tracks the feature request.

**Comment by rtripath89** [comment]
@jprorama : Can we leave the opening up http port as a task in ood main yaml file? Or do you want me to move that to services role as well?

**Comment by jprorama** [comment]
Likely better in the service role considering how these are typically managed.

**Comment by jprorama** [comment]
This was completed with pull request #26.
