### ISSUE TITLE
`ood_uab_ui` role fails with `variable app_name is undefined`

### ISSUE THREAD

**Issue by eesaanatluri** [jprorama/CRI_XCBC#388]
Error: 
The role `ood_uab_ui` fails with an error: `variable app_name is undefined`.

Description:
The var `app_name` was defined in a task and it was used in a different task afterwards, so the scope of the var ends in the task it is defined.  Since the scope of it wasn't defined at a role level (i.e at the start of the role) rather just the task, it considers the variable as undefined.

Solution:
  - Use {{ item }} attribute of the loop for task

**Comment by diedpigs** [comment]
`ood_uab_ui` only exists in `uab-prod` branch
