### ISSUE TITLE
Jupyter notebook needs to option to request memory and slots instead of nodes

### ISSUE THREAD

**Issue by jprorama** [jprorama/CRI_XCBC#61]
The jupyter notebook job submit form doesn't have an option for requesting memory.  This is needed to get beyond the 1G default for jobs. 

Additional the node count selects 1 core per compute node.  It appears the submit form should ask for slots and map to the -n and not -N slurm option.   In fact it should be `-N 1 -n <slots>`  so all the cores are allocated on the same node.  This is the most useful default until more advanced options can be specified.

**Comment by diedpigs** [comment]
Take a look at pull request #62

**Comment by jprorama** [comment]
Fixed by #62
